### PR TITLE
Single-precision

### PR DESCRIPTION
**Pull request by zw0930**
## Description
Single-precision option for RT-CCSD calculations.

## Todos
  - [x] Add single-precision option.
  - [x] Cast F and ERI to sp at the beginning of the calculation. 
  - [x] Initiate needed variables in sp.
  - [x] Make modifications for GPU tensors.
  - [x] Test and check the accuracy.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by bgpeyton** [comment]
@zw0930 it looks like [the dipole is matching to 6 decimal places](https://github.com/CrawfordGroup/pycc/runs/7859253684?check_suite_focus=true#step:9:133), which is just a little short of your `1e-7` threshold. is this a reasonable expectation for the single-precision code, or is that close enough that we shouldn't expect it to match to seven digits?

**Comment by zw0930** [comment]
> 

It matches 7 digits when I tested on my laptop. I will take a closer look at it.

**Comment by zw0930** [comment]
Updated the reference values from the same calculation in double-precision (the old dipole reference values were wrong/incomplete); also changed the difference check in the dipole moment results from 1E-7 to 1E-6. 
The difference in the dipole moment ranges from 1E-7 to 1E-8 which is reasonable for the single-precision calculation when the convergence threshold for the energy and amplitudes is 1E-7. Matching 7 digits is the upper bound of the single-precision arithmetic. In the case of the dipole moment here, it matches 6 or 7 digits.

**Review by lothian — APPROVED** [review]

**Comment by zw0930** [comment]
Thank you for reviewing it. I think it's ready to go.

**Pull request merged**
